include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for EasyMesh
LUCI_DEPENDS:=+luci-base +mesh-ac

PKG_LICENSE:=MIT
PKG_MAINTAINER:=ysuolmai

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
